srcs = \
../DialogTools/3DControlPan.cpp\
../DialogTools/3DDlg.cpp\
../DialogTools/AddCentroidsDlg.cpp\
../DialogTools/AddColumnDlg.cpp\
../DialogTools/AddKeyDBFDlg.cpp\
../DialogTools/ASC2SHPDlg.cpp\
../DialogTools/Bnd2ShpDlg.cpp\
../DialogTools/CCVariableDlg.cpp\
../DialogTools/ConditionViewDlg.cpp\
../DialogTools/CreateGridDlg.cpp\
../DialogTools/CreatingWeightDlg.cpp\
../DialogTools/Dbf2GaussDlg.cpp\
../DialogTools/DBF2SHPDlg.cpp\
../DialogTools/DeleteColumnDlg.cpp\
../DialogTools/FieldCalcBinDlg.cpp\
../DialogTools/FieldCalcLagDlg.cpp\
../DialogTools/FieldCalcRateDlg.cpp\
../DialogTools/FieldCalcSheetDlg.cpp\
../DialogTools/FieldCalcUniDlg.cpp\
../DialogTools/GetDbfFileDlg.cpp\
../DialogTools/HelpMessageDlg.cpp\
../DialogTools/HistIntervalDlg.cpp\
../DialogTools/InverseDistanceDlg.cpp\
../DialogTools/JoinTableDlg.cpp\
../DialogTools/LisaWhat2OpenDlg.cpp\
../DialogTools/MapQuantileDlg.cpp\
../DialogTools/MovieControlPan.cpp\
../DialogTools/PCPDlg.cpp\
../DialogTools/PermutationCounterDlg.cpp\
../DialogTools/ProjectSettingDlg.cpp\
../DialogTools/RandomizationDlg.cpp\
../DialogTools/RangeSettingDlg.cpp\
../DialogTools/RateSmootherDlg.cpp\
../DialogTools/RegProgresBarDlg.cpp\
../DialogTools/RegressionDlg.cpp\
../DialogTools/RegressionProgressReportDlg.cpp\
../DialogTools/RegressionReportDlg.cpp\
../DialogTools/RegressionTitleDlg.cpp\
../DialogTools/SaveCentroidsDlg.cpp\
../DialogTools/SaveLisaDlg.cpp\
../DialogTools/SaveMoranIDlg.cpp\
../DialogTools/SaveRateDlg.cpp\
../DialogTools/SaveRegressionDlg.cpp\
../DialogTools/SaveSelectionDlg.cpp\
../DialogTools/SelectWeightDlg.cpp\
../DialogTools/SHP2ASCDlg.cpp\
../DialogTools/Statistics.cpp\
../DialogTools/ThiessenPolygonDlg.cpp\
../DialogTools/UserConfigDlg.cpp\
../DialogTools/VariableSettingsDlg.cpp\
../DialogTools/Variog2DPairDlg.cpp\
../DialogTools/WeightCharacterDlg.cpp\
../Explore/3DPlotView.cpp\
../Explore/BoxPlotView.cpp\
../Explore/CartogramView.cpp\
../Explore/ConditionalView.cpp\
../Explore/Geom3D.cpp\
../Explore/HistView.cpp\
../Explore/LisaBoxView.cpp\
../Explore/LisaMapView.cpp\
../Explore/MoranGView.cpp\
../Explore/MoranScatterPlotView.cpp\
../Explore/PCPView.cpp\
../Explore/ScatterPlotView.cpp\
../Explore/wxGeneralSplitter.cpp\
../kNN/ANN.cpp\
../kNN/kd_pr_search.cpp\
../kNN/kd_search.cpp\
../kNN/kd_split.cpp\
../kNN/kd_tree.cpp\
../kNN/kd_util.cpp\
../kNN/kNN.cpp\
../mapview.cpp\
../OpenGeoDa.cpp\
../rc/MyAppResources.cpp\
../Regression/DenseMatrix.cpp\
../Regression/DenseVector.cpp\
../Regression/DiagnosticReport.cpp\
../Regression/GalStorage.cpp\
../Regression/mix.cpp\
../Regression/ML_im.cpp\
../Regression/PowerLag.cpp\
../Regression/PowerSymLag.cpp\
../Regression/smile2.cpp\
../Regression/SparseMatrix.cpp\
../Regression/SparseRow.cpp\
../Regression/SparseVector.cpp\
../Regression/Weights.cpp\
../ShapeOperations/shp.cpp\
../ShapeOperations/Gauss.cpp\
../ShapeOperations/GCollector.cpp\
../ShapeOperations/Randik.cpp\
../ShapeOperations/RecordKey.cpp\
../ShapeOperations/shp2cnt.cpp\
../ShapeOperations/shp2gwt.cpp\
../ShapeOperations/AbstractShape.cpp\
../ShapeOperations/BasePoint.cpp\
../ShapeOperations/Box.cpp\
../ShapeOperations/DBF.cpp\
../ShapeOperations/ShapeFile.cpp\
../ShapeOperations/ShapeFileHdr.cpp\
../ShapeOperations/ShapeFileTriplet.cpp\
../TableView.cpp\
../TemplateCanvas.cpp\
../Thiessen/Thiessen.cpp\
../Thiessen/VorUtility.cpp\
../GeneralWxUtils.cpp\
../GenGeomAlgs.cpp\
../GenUtils.cpp\
../logger.cpp\
../MyLogWindow.cpp

hdrs = \
../DialogTools/3DControlPan.h\
../DialogTools/3DDlg.h\
../DialogTools/AddCentroidsDlg.h\
../DialogTools/AddColumnDlg.h\
../DialogTools/AddKeyDBFDlg.h\
../DialogTools/ASC2SHPDlg.h\
../DialogTools/Bnd2ShpDlg.h\
../DialogTools/CCVariableDlg.h\
../DialogTools/ConditionViewDlg.h\
../DialogTools/CreateGridDlg.h\
../DialogTools/CreatingWeightDlg.h\
../DialogTools/Dbf2GaussDlg.h\
../DialogTools/DBF2SHPDlg.h\
../DialogTools/DeleteColumnDlg.h\
../DialogTools/FieldCalcBinDlg.h\
../DialogTools/FieldCalcLagDlg.h\
../DialogTools/FieldCalcRateDlg.h\
../DialogTools/FieldCalcSheetDlg.h\
../DialogTools/FieldCalcUniDlg.h\
../DialogTools/GetDbfFileDlg.h\
../DialogTools/HelpMessageDlg.h\
../DialogTools/HistIntervalDlg.h\
../DialogTools/InverseDistanceDlg.h\
../DialogTools/JoinTableDlg.h\
../DialogTools/LisaWhat2OpenDlg.h\
../DialogTools/MapQuantileDlg.h\
../DialogTools/MovieControlPan.h\
../DialogTools/PCPDlg.h\
../DialogTools/PermutationCounterDlg.h\
../DialogTools/ProjectSettingDlg.h\
../DialogTools/RandomizationDlg.h\
../DialogTools/RangeSettingDlg.h\
../DialogTools/RateSmootherDlg.h\
../DialogTools/RegProgresBarDlg.h\
../DialogTools/RegressionDlg.h\
../DialogTools/RegressionProgressReportDlg.h\
../DialogTools/RegressionReportDlg.h\
../DialogTools/RegressionTitleDlg.h\
../DialogTools/SaveCentroidsDlg.h\
../DialogTools/SaveLisaDlg.h\
../DialogTools/SaveMoranIDlg.h\
../DialogTools/SaveRateDlg.h\
../DialogTools/SaveRegressionDlg.h\
../DialogTools/SaveSelectionDlg.h\
../DialogTools/SelectWeightDlg.h\
../DialogTools/SHP2ASCDlg.h\
../DialogTools/Statistics.h\
../DialogTools/ThiessenPolygonDlg.h\
../DialogTools/UserConfigDlg.h\
../DialogTools/VariableSettingsDlg.h\
../DialogTools/Variog2DPairDlg.h\
../DialogTools/WeightCharacterDlg.h\
../Explore/3DPlotView.h\
../Explore/BoxPlotView.h\
../Explore/CartogramView.h\
../Explore/ConditionalView.h\
../Explore/Geom3D.h\
../Explore/HistView.h\
../Explore/LisaBoxView.h\
../Explore/LisaMapView.h\
../Explore/MoranGView.h\
../Explore/MoranScatterPlotView.h\
../Explore/PCPView.h\
../Explore/ScatterPlotView.h\
../Explore/wxGeneralSplitter.h\
../kNN/ANN.h\
../kNN/ANNperf.h\
../kNN/ANNx.h\
../kNN/kd_pr_search.h\
../kNN/kd_search.h\
../kNN/kd_split.h\
../kNN/kd_tree.h\
../kNN/kd_util.h\
../kNN/pr_queue.h\
../kNN/pr_queue_k.h\
../kNN/values.h\
../mapview.h\
../OpenGeoDa.h\
../Regression/DenseMatrix.h\
../Regression/DenseVector.h\
../Regression/DiagnosticReport.h\
../Regression/GalStorage.h\
../Regression/Link.h\
../Regression/Lite2.h\
../Regression/mix.h\
../Regression/ML_im.h\
../Regression/polym.h\
../Regression/PowerLag.h\
../Regression/PowerSymLag.h\
../Regression/smile.h\
../Regression/SparseMatrix.h\
../Regression/SparseRow.h\
../Regression/SparseVector.h\
../Regression/Weights.h\
../ShapeOperations/Gauss.h\
../ShapeOperations/Randik.h\
../ShapeOperations/RecordKey.h\
../ShapeOperations/shp.h\
../ShapeOperations/shp2cnt.h\
../ShapeOperations/shp2gwt.h\
../ShapeOperations/AbstractShape.h\
../ShapeOperations/BasePoint.h\
../ShapeOperations/Box.h\
../ShapeOperations/DBF.h\
../ShapeOperations/ShapeFile.h\
../ShapeOperations/ShapeFileHdr.h\
../ShapeOperations/ShapeFileTriplet.h\
../ShapeOperations/ShapeFileTypes.h\
../TableView.h\
../TemplateCanvas.h\
../Thiessen/Thiessen.h\
../Thiessen/VorDataType.h\
../GeneralWxUtils.h\
../GenConsts.h\
../GenGeomAlgs.h\
../GenUtils.h\
../logger.h\
../MyLogWindow.h\
../nullstream.h